name: BUILD_CONNECTOR_API

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21.4

      - name: Update & Download Deps
        run: |
            cd connector/
            go mod tidy

      - name: Build Connector API
        run: go build -C connector/ -o connector


