name: ADMIN FLUTTER APP BUILD

on:
  push:
    branches:
      - main
      - dev/app

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.8.1'
      
      - name: Set up working directory
        run: cd apps/admin

      - name: Install dependencies
        run: flutter pub get

      - name: Run tests
        run: flutter test

      - name: Build APK
        run: flutter build apk
